### PR TITLE
Rboost

### PR DESCRIPTION
**Pull request by rahulgayatri23**
Merging OpenMP and Pthread version with MPI branch

### CODE REVIEW

**Comment by rahulgayatri23** [comment]
This is a working version with the boost library.

**Comment by dilawar** [comment]
Need to assign environment variable `NUM_THREADS` to non-zero values (number of threads users want to launch).

**Comment by dilawar** [comment]
@rahulgayatri23  Follow the command line instruction and see if there are other merge issues. You may have favoured `gsl` related code in previous merge.

**Comment by dilawar** [comment]
Need some fixes.

**Pull request merged**
