### PR TITLE
Update moose.py

### PR DESCRIPTION
**Pull request by dilawar**
This caused few scripts to fail on  moose-examples. `chemError_` could not be printed because it was not in scope.

### CODE REVIEW

**Comment by hrani** [comment]
I would like to know which example failed due to this? and from where did you run.
If this is called from electrical model then I have some other fix which should not call chemError_ or I might want to return the errormsg.

**Comment by dilawar** [comment]
In particular,

```
[ 6%] Executing /home/travis/build/BhallaLab/moose-examples/snippets/vectors.py

|| Failed with status 1 
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadKineticModel.py", line 121, in <module>
      main()
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadKineticModel.py", line 90, in main
      modelId = moose.loadModel( filepath, 'model', solver )
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 98, in loadModel
      moose.mooseAddChemSolver(target,method)
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 216, in mooseAddChemSolver
      print( chemError_ )
  UnboundLocalError: local variable 'chemError_' referenced before assignment

```

There are other failed cases which you can review https://travis-ci.org/BhallaLab/moose-examples
Some other are failing because of missing `fixXreacs` module.

All failed scripts are below. Some of them are due to missing dependencies.

- [ snippets/loadSbmlmodel.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/loadSbmlmodel.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  (0.942477796076938, 0.2827433388230814)
  ('Current clamp connected:', <moose.SingleMsg: id=5, dataIndex=2, path=/Msgs[0]/singleMsg[2]>)
  Vm saved to Vm.dat
  K conductance saved to gK.dat
  Na conductance saved to gNa.dat
  on2.7/dist-packages/moose/chemUtil/__init__.py", line 2, in <module>
      from .add_Delete_ChemicalSolver import *
    File "/usr/lib/python2.7/dist-packages/moose/chemUtil/add_Delete_ChemicalSolver.py", line 3, in <module>
      from fixXreacs import fixXreacs
  ImportError: No module named fixXreacs
```
- [ tutorials/ChemicalBistables/strongBis.py ](https://github.com/BhallaLab/moose-examples/blob/master/tutorials/ChemicalBistables/strongBis.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  ('\nElements Matching:', '/alfa/bravo/#[TYPE=HHChannel2D]')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]')
  ('\nElements Matching:', '/alfa/bravo/#[ISA=HHChannel]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]')
  ('\nElements Matching:', '/alfa/bravo/#[ISA=ChanBase]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]')
  ('\nElements Matching:', '/alfa/bravo/#[TYPE=ChanBase]')
  ('\nElements Matching:', '/alfa/bravo/charl?e')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]')
  ('\t', '/alfa[0]/bravo[0]/charlee[0]')
  ('\nElements Matching:', '/alfa/bravo/fox#')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]')
  ('\t', '/alfa[0]/bravo[0]/foxtail[0]')
  ('\nElements Matching:', '/##[ISA=ChanBase]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]/golf[0]')
  ('\nElements Matching:', '/##[FIELD(name)=echo]')
  ('\t', '/alfa[0]/echo[0]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]')
  ('\nElements Matching:', '/##[FIELD(name)==echo]')
  ('\t', '/alfa[0]/echo[0]')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]')
  ('\nElements Matching:', '/alfa/##[FIELD(Gbar)<1e-6]')
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element echo
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element foxtail
  0: Error: SetGet::strGet: Field Gbar not found on Element charlee
  0: Error: SetGet::strGet: Field Gbar not found on Element bravo
  0: Error: SetGet::strGet: Field Gbar not found on Element delta
  0: Error: SetGet::strGet: Field Gbar not found on Element papa
  0: Error: SetGet::strGet: Field Gbar not found on Element echo
  ('\t', '/alfa[0]/bravo[0]/charlie[0]', 1e-09)
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]', 5e-07)
  ('\nElements Matching:', '/alfa/##[FIELD(Gbar)=1e-6]')
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element echo
  0: Error: SetGet::strGet: Field Gbar not found on Element gateX
  0: Error: SetGet::strGet: Field Gbar not found on Element gateY
  0: Error: SetGet::strGet: Field Gbar not found on Element gateZ
  0: Error: SetGet::strGet: Field Gbar not found on Element foxtail
  0: Error: SetGet::strGet: Field Gbar not found on Element charlee
  0: Error: SetGet::strGet: Field Gbar not found on Element bravo
  0: Error: SetGet::strGet: Field Gbar not found on Element delta
  0: Error: SetGet::strGet: Field Gbar not found on Element papa
  0: Error: SetGet::strGet: Field Gbar not found on Element echo
  ('\nElements Matching:', '/alfa/bravo/#[TYPE!=HHChannel]')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]', ', class:', 'HHChannel2D')
  ('\t', '/alfa[0]/bravo[0]/foxtail[0]', ', class:', 'Neutral')
  ('\t', '/alfa[0]/bravo[0]/charlee[0]', ', class:', 'Neutral')
  ('\nElements Matching:', '/alfa/##')
  ('\t', '/alfa[0]/bravo[0]', ', class:', 'Compartment')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]', ', class:', 'HHChannel')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/gateX[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/gateY[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/gateZ[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]', ', class:', 'HHChannel2D')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]/gateX[0]', ', class:', 'HHGate2D')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]/gateY[0]', ', class:', 'HHGate2D')
  ('\t', '/alfa[0]/bravo[0]/foxtrot[0]/gateZ[0]', ', class:', 'HHGate2D')
  ('\t', '/alfa[0]/echo[0]', ', class:', 'Neutral')
  ('\t', '/alfa[0]/echo[0]/delta[0]', ', class:', 'DiffAmp')
  ('\t', '/alfa[0]/echo[0]/papa[0]', ', class:', 'PulseGen')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]', ', class:', 'Pool')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]/golf[0]', ', class:', 'HHChannel')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]/golf[0]/gateX[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]/golf[0]/gateY[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/charlie[0]/echo[0]/golf[0]/gateZ[0]', ', class:', 'HHGate')
  ('\t', '/alfa[0]/bravo[0]/foxtail[0]', ', class:', 'Neutral')
  ('\t', '/alfa[0]/bravo[0]/charlee[0]', ', class:', 'Neutral')
```
- [ snippets/loadKineticModel.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/loadKineticModel.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadKineticModel.py", line 121, in <module>
      main()
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadKineticModel.py", line 90, in main
      modelId = moose.loadModel( filepath, 'model', solver )
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 98, in loadModel
      moose.mooseAddChemSolver(target,method)
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 216, in mooseAddChemSolver
      print( chemError_ )
  UnboundLocalError: local variable 'chemError_' referenced before assignment
```
- [ snippets/helloMoose.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/helloMoose.py)
```
```
- [ snippets/crossComptOscillator.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/crossComptOscillator.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  timeout: the monitored command dumped core
```
- [ izhikevich/demogui_qt.py ](https://github.com/BhallaLab/moose-examples/blob/master/izhikevich/demogui_qt.py)
```
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/izhikevich/demogui_qt.py", line 50, in <module>
      import PyQt4.Qwt5 as Qwt
  ImportError: No module named Qwt5
```
- [ tutorials/ChemicalBistables/simpleBis.py ](https://github.com/BhallaLab/moose-examples/blob/master/tutorials/ChemicalBistables/simpleBis.py)
```
```
- [ parallelSolver/Fig2_v4.py ](https://github.com/BhallaLab/moose-examples/blob/master/parallelSolver/Fig2_v4.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/parallelSolver/Fig2_v4.py", line 10, in <module>
      import rdesigneur as rd
    File "/usr/lib/python2.7/dist-packages/rdesigneur/__init__.py", line 4, in <module>
      from rdesigneur.rdesigneur import *
    File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py", line 32, in <module>
      import fixXreacs
  ImportError: No module named fixXreacs
```
- [ snippets/loadCspaceModel.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/loadCspaceModel.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadCspaceModel.py", line 74, in <module>
      main()
    File "/home/travis/build/BhallaLab/moose-examples/snippets/loadCspaceModel.py", line 58, in main
      modelId = moose.loadModel( 'Osc.cspace', 'model', 'gsl' )
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 98, in loadModel
      moose.mooseAddChemSolver(target,method)
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 216, in mooseAddChemSolver
      print( chemError_ )
  UnboundLocalError: local variable 'chemError_' referenced before assignment
```
- [ snippets/tweakingParameters.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/tweakingParameters.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/snippets/tweakingParameters.py", line 74, in <module>
      main()
    File "/home/travis/build/BhallaLab/moose-examples/snippets/tweakingParameters.py", line 46, in main
      modelId = moose.loadModel( mfile, 'model', 'gsl' )
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 98, in loadModel
      moose.mooseAddChemSolver(target,method)
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 216, in mooseAddChemSolver
      print( chemError_ )
  UnboundLocalError: local variable 'chemError_' referenced before assignment
```
- [ snippets/switchKineticSolvers.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/switchKineticSolvers.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  Traceback (most recent call last):
    File "/home/travis/build/BhallaLab/moose-examples/snippets/switchKineticSolvers.py", line 137, in <module>
      main()
    File "/home/travis/build/BhallaLab/moose-examples/snippets/switchKineticSolvers.py", line 86, in main
      modelId = moose.loadModel( mfile, 'model', solver )
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 98, in loadModel
      moose.mooseAddChemSolver(target,method)
    File "/usr/lib/python2.7/dist-packages/moose/moose.py", line 216, in mooseAddChemSolver
      print( chemError_ )
  UnboundLocalError: local variable 'chemError_' referenced before assignment
```
- [ tutorials/ChemicalOscillators/repressillator.py ](https://github.com/BhallaLab/moose-examples/blob/master/tutorials/ChemicalOscillators/repressillator.py)
```
```
- [ tutorials/ChemicalOscillators/relaxationOsc.py ](https://github.com/BhallaLab/moose-examples/blob/master/tutorials/ChemicalOscillators/relaxationOsc.py)
```
```
- [ snippets/reacDiffConcGradient.py ](https://github.com/BhallaLab/moose-examples/blob/master/snippets/reacDiffConcGradient.py)
```
  No CPU information available. Assuming single core.
  No CPU information available. Assuming single core.
  on node 0, numNodes = 1, numCores = 1
  timeout: the monitored command dumped core

**Comment by dilawar** [comment]
Probably #292 makes it redundant.

**Comment by hrani** [comment]
The error might not be because of `chemError_` is referenced before assignment.
The variable is defined in the moose.py file.
Can you check is /usr/lib/python2.7/dist-packages/ has copied the moose.chemUtil and  

also parallelSolver/Fig2_v4.py  is complains about 

File "/usr/lib/python2.7/dist-packages/rdesigneur/rdesigneur.py", line 32, in <module>
      import fixXreacs
  ImportError: No module named fixXreacs
 
But when run on local system Fig2_v4.py it runs.
So assuming somewhere in /usr/lib/python2.7/dist-packages... not copying the files correctly or some issue with path.

Because travis is still failing

**Comment by dilawar** [comment]
`fixXreacs.py` is outside `python/moose` folder. It won't be (and can't be) inside any of the package. Either move it to `python/moose` folder or inside `python/rdesigneur` folder and change the import statement appropriately.

Any python file to be in release, should be inside an appropriate folder.

**Pull request closed without merging**
