### PR TITLE
Fixes to Issue 414

### PR DESCRIPTION
**Pull request by dilawar**
This PR tracks the progress on #414

### CODE REVIEW

**Comment by dilawar** [comment]
@bhanu151 

- Download the attachment.
- Build MOOSE from this branch
```
$ git clone https://github.com/dilawar/moose-core -b issue_414 --depth 10
$ cd moose-core 
$ mkdir _build
$ cd _build && cmake .. && make -j4
```
- Run the script.

I am getting following now:

```
[dilawars@Zoro _build (issue_414)]$ (cd Supplementary/ && PYTHONPATH=$(pwd)/../../python python3 Fig6_generate_data.py --fnumber 0 --sequence 1234)
1234 [0.1234, 1.234, 2.34, 3.4000000000000057, 4] Fig6_data.0.1234
[INFO] doLoadModel: In doLoadModel for SWC
ReadSwc: VHC-neuron.CNG.swc    : NumSegs = 3016, bad = 0, Validated = 1, numBranches = 94
ReadSwc::diagnostics:        undef:     0
ReadSwc::diagnostics:         soma:     3
ReadSwc::diagnostics:         axon:     0
ReadSwc::diagnostics:         dend:   881
ReadSwc::diagnostics:       apical:  2041
ReadSwc::diagnostics:       dend_f:    12
ReadSwc::diagnostics:       dend_e:    14
ReadSwc::diagnostics:       custom:     0
ReadSwc::diagnostics:          bad:     0
ReadSwc::diagnostics:        undef:     0
ReadSwc::diagnostics:       axon_f:     0
ReadSwc::diagnostics:       axon_e:     0
ReadSwc::diagnostics:     apical_f:    32
ReadSwc::diagnostics:     apical_e:    33
DeprecationWarning:: Use Soitch::reacSystemPath instead. In the future, it will be an error.
DeprecationWarning:: Use Soitch::reacSystemPath instead. In the future, it will be an error.
DeprecationWarning:: Use Soitch::reacSystemPath instead. In the future, it will be an error.
Rdesigneur: Elec model has 3016 compartments and 5834 spines on 3016 compartments.
    Chem part of model has the following compartments: 
    | In dend, 5985 voxels X 28 pools
    | In spine, 5834 voxels X 7 pools
    | In psd, 5834 voxels X 8 pools
1.0 + 1.0 * cos( 6.283 * t * 4.0 )^2
     NUM-GABA =  3013
Starting Spatial Output
Starting PeriodicOutput
Current sim time =  0.0 , user time =  222.33329463005066
0.1234 1131 1763 head1763 apical_36_3
0.1234 2000 3551 head3551 apical_70_4
0.1234 500 753 head753 dend_16_9
0.1234 1490 2451 head2451 apical_52_5
1.234 1131 1767 head1767 apical_36_6
1.234 2000 3555 head3555 apical_70_5
1.234 500 757 head757 dend_16_10
1.234 1490 2455 head2455 apical_52_7
2.34 1131 1772 head1772 apical_36_8
2.34 2000 3560 head3560 apical_70_8
2.34 500 762 head762 dend_16_12
2.34 1490 2460 head2460 apical_52_9
3.4000000000000057 1131 1776 head1776 apical_36_10
3.4000000000000057 2000 3564 head3564 apical_70_11
3.4000000000000057 500 766 head766 dend_16_13
3.4000000000000057 1490 2464 head2464 apical_52_10
4 1131 1779 head1779 apical_36_11
4 2000 3567 head3567 apical_70_12
4 500 769 head769 dend_16_14
4 1490 2467 head2467 apical_52_11
Current sim time =  1.0 , user time =  808.9062378406525
Current sim time =  2.0 , user time =  1415.3131108283997
````
Still running but I think its good enough for you to get started.
Update this ticket if there are issues with other file.
[Supplementary_2020_06_07__17_41_15.tar.gz](https://github.com/BhallaLab/moose-core/files/4742033/Supplementary_2020_06_07__17_41_15.tar.gz)

**Comment by upibhalla** [comment]
Awaiting checks.

**Comment by dilawar** [comment]
The PR has passed https://travis-ci.org/github/BhallaLab/moose-core/jobs/695648818 . Seem like there is some issue in reporting the status back to github.

**Comment by dilawar** [comment]
Closing and reopening the PR for travis trigger.

**Comment by hrani** [comment]
can you resolve conflicts I removed in pyRun.cpp then we can merge

**Comment by dilawar** [comment]
@hrani Resolved the conflict.

**Comment by hrani** [comment]
@bhanu151 saying working so merging

**Pull request merged**
