### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by keszybz**
This series implements Python 3 support. It's a reworking of my series from 2014.

The test cases in tests/ pass, apart from the ones which also fail under Python 2 (`issues/issue_34.py` and `python/test_sbml.py`).

Apart from that it successfully runs our single-neuron model at https://github.com/neurord/spspine, with identical results under Python 2 and 3.

There should be no changes to functionality, except for extended slicing support (2nd commit).

### CODE REVIEW

**Comment by dilawar** [comment]
Adding @subhacom .

**Comment by keszybz** [comment]
Rebased to fix the merge conflict.

**Comment by subhacom** [comment]
Will take a look over the weekend.

**Comment by dilawar** [comment]
This seems to break moose-gui. Adding @hrani .

**Pull request merged**
