### PR TITLE
Enabled  `moose.util` and added tests

### PR DESCRIPTION
**Pull request by dilawar**
- [x] `moose.util` module is fixed with `absolute_import`
- [x] Added tests for moose.utils.
- [x] Travis pass

### CODE REVIEW

**Comment by hrani** [comment]
in moose.py file, check's where made to see if libSBML is installed (try and exception section) which is removed.
Where is this moved to? or is there any other way to check before importing the files.
If not, I preferred to keep it here at one place (moose.py file)

**Comment by dilawar** [comment]
Did you mean this 

```
+sbmlImport_, sbmlError_ = True, ''
+try:
+    import moose.SBML.readSBML as _readSBML
+    import moose.SBML.writeSBML as _writeSBML
+except Exception as e:
+    sbmlImport_ = False
+    sbmlError_ = '%s' % e
```

They are there in `moose.py` file. \

You can review the appropriate file by commenting on lines where you see the problem. By clicking on `Files changed`.  It will reduce the guess work. Details are here https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/

**Comment by hrani** [comment]
I am not sure what kind of guess work was needed, its clearly saying in moose.py, libSBML try and exception code...
Guess your latest commit has failed building in travis, is not allowing to merge the pull request

**Comment by dilawar** [comment]
```
in moose.py file, check's were made to see if libSBML is installed (try and exception section) which is removed.```

It is still there, not removed. See the `moose.py` file. You can comment on the file itself if something is missing.

Fixes are required to make the build pass, there is no need to close the PR.

**Pull request merged**
