### PR TITLE
changes to sbml and merge files

### PR DESCRIPTION
**Pull request by hrani**

### CODE REVIEW

**Comment by dilawar** [comment]
Add following lines in .travis.ym file. 

~~~
addons:
    apt:
      update: true
~~~

**Comment by hrani** [comment]
Yes it worked.
Thank you

**Comment by hrani** [comment]
changes made wrt to diffusion solver method

**Comment by dilawar** [comment]
Update tests files in `tests/python` folder in this PR itself. Currently `moose.mooseaddChemSolver` is not behaving well.

**Comment by dilawar** [comment]
Just a comment, after this merge, default solver will not be 'gsl' in most scripts. I am merging it because of request by developer for camp course usage.

@upibhalla  Needs final decision on default solver type `ee` or `gsl`. After this merge, it is most likely `ee` in all script unless set by user using `moose.mooseaddChemSolver( 'model', 'gsl')` etc.

**Pull request merged**
