### PR TITLE
Added support for `fmod`, `rand()` and `rand2(a, b)` in muparser., better exception handling etc.

### PR DESCRIPTION
**Pull request by dilawar**

### CODE REVIEW

**Comment by subhacom** [comment]
Hi Dilawar,
  I would suggest you to be very careful with random number generation.
MOOSE already has the Marsenne twister built in. If you do not use the same
rng in Function, there may be extremely hard to find bugs in simulations.
These usually result in the probability distributions not being
uncorrelated and other statistical issues. Also, I do not see any seeding
function added.
Recommend reading Knuth vol 2.

Best,
- Subhasis

**Comment by dilawar** [comment]
In this, I am calling rand() from standard library without setting the seed. I can probably add two more functions `rands(seed)` and `rands(a, b, seed)` to make sure that simulation results are reproducible.

**Comment by subhacom** [comment]
Hi,

On Mar 7, 2016 11:16 PM, "Dilawar Singh" <notifications@github.com> wrote:
>
> In this, I am calling rand() from standard library without setting the
seed. I can probably add two more functions rands(seed) and rands(a, b,
seed) to make sure that simulation results are reproducible.
>
The issue is deeper than reproducibility. Please just use the Mersenne
twister included in moose.
Thanks,
   Subha

**Comment by dilawar** [comment]
Hi Subha,

We had a chat about random number generation in MOOSE. We need to rank various
options according to following criteria (given that we will have multiple object
using their own "good" random number generators):
    
1. Efficiency, how fast they are.
2. Scalable
3. Thread safe
4. Independence. Do each generator share any data? If they do, parallelization
may not produce great speedup (as we realized in the case of gsl+openmpi).
5. Others. I couldn't think of any other.

As for now, for muparser, I prefer <random> from c++11 (since most compiler now
has this support), and fallback to <cstdlib> (which I presume generates bad
sequences). Once we settle on which one to use, I'll merge the pull request. 

-- 
best,
    Dilawar

**Comment by subhacom** [comment]
Hi,

On Tue, Mar 8, 2016 at 12:39 AM, Dilawar Singh <notifications@github.com>
wrote:

> We had a chat about random number generation in MOOSE. We need to rank
> various
> options according to following criteria (given that we will have multiple
> object
> using their own "good" random number generators):
>
> 1. Efficiency, how fast they are.
> 2. Scalable
> 3. Thread safe
> 4. Independence. Do each generator share any data? If they do,
> parallelization
> may not produce great speedup (as we realized in the case of gsl+openmpi).
> 5. Others. I couldn't think of any other.
>

I completely agree. I am sure you are aware that (1) C++11 uses existing
RNG algorithms (including MT) and the fastest may not be good for
simulations, (2)  parallel RNG is an active research topic and the parallel
MT (DC) has issues.


>
> As for now, for muparser, I prefer <random> from c++11 (since most
> compiler now
> has this support), and fallback to <cstdlib> (which I presume generates bad
> sequences). Once we settle on which one to use, I'll merge the pull
> request.
>

I would have agreed if the main goal was to enhance muParser, in which case
using the C++ standard library would have been a must. However, when you
introduce two independent RNG, the user has to make sure both are
initialized properly and even in the simple case of serial simulations just
seeding them differently may not produce the right statistics. I found that
C++11 includes MT as an engine, so I would think just making sure that
there is just one global RNG in a serial simulation should be easy.

You may also want to check how PCSIM and NEURON handled parallel RNG and
the issues they faced.

Best,
  Subha

**Comment by upibhalla** [comment]
Dear Subha,
     We need to plan for having > 10K independent RNGs (on different 
threads). So they need to be clean standalone objects and in addition to 
being thread-safe, they should be so independent that the threading 
system does not try to do synchronization. We have run into this in a 
bad way with the GSL solver.

Best,
     Upi

**Comment by dilawar** [comment]
moose_stl_boost_ratio


Simple benchmark. BOOST is 3x, and STL is 2x than inbuilt MOOSE random number generator.

**Comment by dilawar** [comment]
I can use the inbuilt MOOSE random number generator.

**Comment by dilawar** [comment]
Updated benchmarks (added http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html) . BOOST is 10x than current MOOSE implementation; STL is 2x 

output

**Comment by dilawar** [comment]
Merging the pull request with STL as default implementation for now. Keeping the issue close. Many other commits are getting accumulated into this pull request; I don't know a way to separate them.

This also fixes issue #84

**Pull request merged**
