### PR TITLE
Gpu

### PR DESCRIPTION
**Pull request by dharmasam9**
Almost production ready gpu code for hsolve.

### CODE REVIEW

**Comment by dilawar** [comment]
Build failed on my local machine. Please check if this compiles on your machine. 
Suggest the changes to compile it on local machine.

**Comment by dharmasam9** [comment]
I have note resolved merge conflicts of dharmasam9/gpu with BhallaLab/master. Can you roll back the commit 37a31f8d1b3feecf487473d5cf43349bef5c7bf7 and #191  pull request. I had plan of appending commits to this PR after discussing some things.

**Comment by dilawar** [comment]
> after discussing some things.

Can these be put here?

**Comment by dharmasam9** [comment]
I had coded other versions for solving the matrix on CPU. They are not bounded #ifdef USE_CUDA. Should I remove such code outside or keep it while resolving conflicts ?

**Comment by dilawar** [comment]
Try to keep as much code as possible. Put them between

#if 0

#endif 

with a comment what this code does.

**Pull request merged**
