### PR TITLE
NeuroML2 updates

### PR DESCRIPTION
**Pull request by pgleeson**
Examples (passive & HH) work now in python 3

### CODE REVIEW

**Comment by analkumar2** [comment]
I'm working on resolving some issues with moose.copy of objects that already exist here: https://github.com/analkumar2/moose-core/tree/NeuroML2

**Comment by pgleeson** [comment]
Thanks @analkumar2. Let me know if you need me to check anything.

**Comment by hrani** [comment]
Anal let me know if this is good to go to main branch. we can push it to main branch

**Comment by pgleeson** [comment]
Replaced by #448

**Pull request closed without merging**
