### PR TITLE
check is made if solver has space while reading/writing SBML files,sm…

### PR DESCRIPTION
**Pull request by hrani**
…all change to port the code to py3

### CODE REVIEW

**Comment by dilawar** [comment]
Merged into #412

**Comment by dilawar** [comment]
@hrani I accidentally overwrote your master branch. Not sure why your fork allowed this mistake: allowing me to push to your master branch. Anyway, I've opened #412 which brings in your changes as well.

**Comment by hrani** [comment]
🤦‍♀️🤦‍♀️🤦‍♀️🤦‍♀️Why why
Anyway I will check on Monday. I try to follow my routine work that way I
don’t work on Sunday. Will check on Monday.

**Comment by dilawar** [comment]
Thanks. I didn't see which master I was writing the changes to. 

Probably you want to check the settings in your fork and make sure that none else can write changes to your repository to avoid such things in the future. I assumed that I could not write to your fork but that definately was not true.

**Comment by dilawar** [comment]
Fortunately, I pulled them into my forks before. You can get them from here if something breaks https://github.com/BhallaLab/moose-core/pull/410/commits/15b49b4499d237bb9ebafde6d0feff8bceb6b9be

**Comment by hrani** [comment]
My local system copy will be safe, so I can push back my changes

**Comment by hrani** [comment]
I though my repo will not allow someone to write will that also.

**Pull request closed without merging**
