### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dilawar**
Updated installation instructions.

- Removed open build service repo.
- Added nightly version.

### CODE REVIEW

**Comment by dilawar** [comment]
@hrani Reminder.

**Comment by hrani** [comment]
Will you be replacing what is already exist in moose->README
https://github.com/BhallaLab/moose

with this?

**Comment by dilawar** [comment]
Not immediately. I guess you meant packages?

Packages will be available for this release. For the next, I'd like to see all components could be installed using pip . 

⁣Sent from handheld device. Pardon the typos and brevity.

**Comment by hrani** [comment]
Even for Package->release, "About", "Documentation","Author" details should go right

**Comment by dilawar** [comment]
When the release is ready, I'll edit the description in main repo as well (assuming you meant instructions on https://GitHub.com/bhallalab/moose ). 

These changes touches only this repository.

**Comment by dilawar** [comment]
Let me summaries again since I am lost now. Probably it will make it clear. This PR adds following lines to README.md . So I am only going to comment what these additional lines means:

```
To install `nightly` build:
    $ pip install pymoose --user --pre --upgrde
    
Have a look at examples, tutorials and demo here https://github.com/BhallaLab/moose-examples.
```

i.e. the instructions added to README.md file here i.e. https://github.com/BhallaLab/moose-core/blob/master/README.md . They are not in contradiction to the instructions in https://github.com/BhallaLab/moose/blob/master/INSTALL.md which are the instruction to install the 'stable' version.

**Pull request merged**
