### PR TITLE
HOTFIX | Issue 402

### LINKED ISSUE #402: isinstance for neutral object returning false
Script is attached. Reported by @hrani over email

```
n = moose.Neutral('/r') 
print isinstance(n,Neutral) 
```
moose-core commit "ec9e209b" when I am checking a Neutral object's
isinstance it print out 'True' (ofcourse if its Neutral object) 

But 

moose-core commit "9489b"  it print out 'False' 

Also 

when I query moose.le('/'), I am not sure if this is change from moose
to _moose.moose but do check. 

Let me know if I am doing any wrong 

File "../test.py", line 14, in <module>
    print moose.le('/r')
AttributeError: 'module' object has no attribute 'le' 

Sample code is attached 

[test.py.txt](https://github.com/BhallaLab/moose-core/files/4427489/test.py.txt)

### PR DESCRIPTION
**Pull request by dilawar**
@hrani This should fix #402. 

I've added your script to the tests (https://github.com/BhallaLab/moose-core/pull/404/files#diff-748ee830a0d2cdd7c9aeb015aeccd69a). The new API will also has it as a test case.

### CODE REVIEW

**Comment by dilawar** [comment]
@hrani this can be tested and merged now.

**Comment by upibhalla** [comment]
Please see my comment on lab notes.
-- Upi

**Comment by hrani** [comment]
The test.py script and also moose-gui works with isinstance.

But in gui code, I have bypassed this, now I small function to get the classname and check for the type.

**Comment by dilawar** [comment]
> The test.py script and also moose-gui works with isinstance.
> 
> But in gui code, I have bypassed this, now I have small function to get the classname of the object and check for the type.

See Upi's comment here https://labnotes.ncbs.res.in/bhalla/new-python-bindings-are-alpha-now . Probably I can map `isinstance` to `.isA` function later but its good to *not rely* on `isinstance` method. It will help in performance of new bindings as well. 

Anyway merge this PR, this does fix this issue without any performance penalty.

**Comment by hrani** [comment]
I did read the labnotes, but before this I had already changed my code, now its doesn't depend on instance of Neutral, I check object's for classname.

**Comment by dilawar** [comment]
> I did read the labnotes, but before this I had already changed my code, now its doesn't depend on instance of Neutral, I check object's for classname.

Be careful with the `className`, it won't check of base class. For example, if you are checking for Pool, it will ignore `PoolBase`. Use `.isA` which is short for`isAncestor`. It will work on a.isA['Pool'] will work on PoolBase as well.

**Comment by dilawar** [comment]
@upibhalla This can be merged.

**Comment by dilawar** [comment]
Updated PR.

**Comment by hrani** [comment]
Since 405 is merged and I see all the changes exist should this (402) PR need to merge?

**Comment by dilawar** [comment]
Contained in #405 .

**Pull request closed without merging**
