### PR TITLE
Adds new solver 'LSODA`

### PR DESCRIPTION
**Pull request by dilawar**
Added new solver based on 'LSODA' method.

- This is a CPP version of the LSODA library for integration into MOOSE simulator. These source code are released under MIT license which is compatible with MOOSE. See `Credit` below.
- Adds three tests (1 python). Results are equivalent to scipy's `lsoda` solver.

Following changes are made to this version:

- Used `<array>` and `<vector>` instead of raw array where-ever possible.
- Craeted a class `LSODA` and added a function to integrate it smoothly with moose.
- Various tweaks in various functions especially initialization.
- Core computing functions starts with index `1` rather than 0; this is hidden away from MOOSE api.

The performance of this solver is really good. In debug mode, on a small model, I got 6.7x speedup without any multi-threading. The solver is not recommended for stiff systems. Once it is integrated we do more profiling vis-a-vis standard RK5 solver.

# Licensing

Work by Heng Li was released under MIT Incense which is less restrictive than GNU-GPLv3. [See here](https://stackoverflow.com/questions/3902754/mit-vs-gpl-license). The LSODA class is released under the same license. 

# TODO 

- [x] Use `Ksolve` parameters to set error tolerance.
- [x] Add multi-threading support if possible.

# Logs

https://docs.google.com/document/d/e/2PACX-1vQ3wU9xiMSMVcluDrNSzuSGHsttOqAqc8xN4a9qo7wFfYjwl-0KhKyY1LlM5XkQ_5CqJd3eFnUCYiAb/pub

# Credit

The original was aquired from http://www.ccl.net/cca/software/SOURCES/C/kinetics2/index.shtml and modified by Heng Li <lh3lh3@gmail.com>. Heng merged several C files into one and added a simpler interface. His version can be found http://lh3lh3.users.sourceforge.net/download/lsoda.c .

### CODE REVIEW

**Comment by dilawar** [comment]
Loss of accuracy with LSODA but speed is excellent.  Following is the reference run; it took ~0.4 sec.

image

Here is run with `LSODA` after setting `ksolve.method = "lsoda"'. It took ~0.07 sec but the precision is bit lost.

image

**Comment by dilawar** [comment]
Though LSODA is fast, it is not suitable for being the default solver. It fails on most multi-scale models. BOOST ode solvers are doing better though than GSL solver.

**Comment by upibhalla** [comment]
Dilawar, please let me know when this is ready to be merged. From the comments and from the checks it seems that LSODA isn't ready yet.
- Upi

**Comment by dilawar** [comment]
Tests have passed. This can now be 'Squashed and Merged'.

**Comment by dilawar** [comment]
Merged into #392

**Pull request closed without merging**
