### PR TITLE
Build python in build dir (2)

### PR DESCRIPTION
**Pull request by keszybz**
Second version of #66.

The goal is to build the python extension module without touching anything outside of the build directory. So the compiled module is placed in the build directory. This is especially useful when building for multiple python versions.

It also makes the build process a bit more standard (under Linux) by using pkg-config and standard python extension module extension under Python 3.

### CODE REVIEW

**Comment by dilawar** [comment]
Travis reports the following error in build process:

```
Scanning dependencies of target copy_python_files
[ 98%] Copying python files to build directory
[ 98%] Built target copy_python_files
CMakeFiles/_moose.dir/build.make:80: *** missing separator.  Stop.
make[1]: *** [CMakeFiles/_moose.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by dilawar** [comment]
Adding `VERBATIM` to `add_custom_command` fixes the build failure
        ```
                                                                         
add_custom_target(copy_python_files                                              
     COMMAND ${CMAKE_COMMAND} -E copy_directory                                   
     ${CMAKE_CURRENT_SOURCE_DIR}/python                                           
     ${CMAKE_CURRENT_BINARY_DIR}/python                                           
    COMMENT "Copying python files to build directory"                            
     VERBATIM                                                                     
)       
```

**Comment by keszybz** [comment]
Right, from the documentation it seems that VERBATIM is something that should be always used. Force pushed with the addition.

**Comment by keszybz** [comment]
OK, let's hope that this version is finally compatible with Python 3.2.

**Comment by keszybz** [comment]
It seems to be failing in tests. I think this is because of the way `sys.path` is modified in test files and gets the wrong directory (`python` in srcdir, not `_build/python`). I'll prepare a separate patch for that, but not before Monday.

**Comment by keszybz** [comment]
Updated commits which set `sys.path` properly. The tests should now pass.

Also new is using pkg-config for tinyxml, muparser, libsml, and libxml2.

**Comment by dilawar** [comment]
Seems like deletion of file broke @hrani  moose-gui .

**Comment by dilawar** [comment]
Accepting.

`PkgConfig` is available for cmake-2.8 which is the minimum required to build moose-packages on open-build-service. 

Thanks for making cmake script cleaner and more consistent.

**Comment by dilawar** [comment]
I had to remove `muparser` search using `pkg-config`. The private `muparser` has extended to support floating mod and rand number generating functions. #76 .

We now always compile and statically link the private mu-parser. Commit 5e1af00b600ca2833 implements these functions in mu-parser.

**Pull request merged**
